In [20]:
from google.colab import drive

# Autoriser l'accès à Google Drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [21]:
import pandas as pd, io, re
from pathlib import Path

chemin = Path('/content/drive/MyDrive/Salmane Khaoula-Zaaiter Oumaima-Fin3-TP2/FMI DATA.xls')
if not chemin.is_file():
    raise FileNotFoundError(f'Fichier introuvable : {chemin}')

# 1) lire le texte (essayer plusieurs encodages)
texte = None
for enc in ('utf-8-sig', 'utf-16', 'cp1252', 'latin-1'):
    try:
        texte = chemin.read_text(encoding=enc)
        break
    except UnicodeError:
        continue

lignes = [l for l in texte.splitlines() if l.strip()]

# 2) trouver la ligne d'en-tête (elle contient 'Facility' et 'Date of')
i_entete = next(i for i, l in enumerate(lignes) if 'Facility' in l and 'Date of' in l)

# 3) garder seulement les lignes de données (contenant une date au format "Mois jj, aaaa" en deuxième colonne)
# Les lignes de données ont la structure : Nom du programme [TAB] Date de début [TAB] Date de fin [TAB] ...
motif = re.compile(r'^[^\t]+\t\s*[A-Z][a-z]+ \d{1,2}, \d{4}\t')
donnees = [l for l in lignes[i_entete + 2:] if motif.match(l)]

# Recréer le CSV tabulaire à partir de la ligne d'en-tête principale et des données
en_tete_propre = "Facility\tDate of Arrangement\tExpiration Date\tAmount Agreed\tAmount Drawn\tAmount Outstanding"
df = pd.read_csv(io.StringIO('\n'.join([en_tete_propre] + donnees)),
                 sep='\t', thousands=',')

# Formater les colonnes
df.columns = ['programme', 'date_accord', 'date_expiration', 'montant_accorde', 'montant_tire', 'montant_restant']
df['date_accord'] = pd.to_datetime(df['date_accord'].str.strip(), format='%b %d, %Y', errors='coerce')
df['annee_accord'] = df['date_accord'].dt.year

display(df.head(10))
print('Dimensions :', df.shape)

,programme,date_accord,date_expiration,montant_accorde,montant_tire,montant_restant,annee_accord
0,Resilience and Sustainability Facility,2023-09-28,"Apr 02, 2025",1000000,562500,562500,2023
1,Flexible Credit Line,2023-04-03,"Apr 02, 2025",3726200,0,0,2023
2,Precautionary and Liquidity Line,2018-12-17,"Apr 07, 2020",2150800,2150800,537700,2018
3,Precautionary and Liquidity Line,2016-07-22,"Jul 21, 2018",2504000,0,0,2016
4,Precautionary and Liquidity Line,2014-07-28,"Jul 21, 2016",3235100,0,0,2014
5,Precautionary and Liquidity Line,2012-08-03,"Jul 27, 2014",4117400,0,0,2012
6,Standby Arrangement,1992-01-31,"Mar 31, 1993",91980,18396,0,1992
7,Standby Arrangement,1990-07-20,"Mar 31, 1991",100000,48000,0,1990
8,Standby Arrangement,1988-08-30,"Dec 31, 1989",210000,210000,0,1988
9,Standby Arrangement,1986-12-16,"Apr 30, 1988",230000,230000,0,1986

Dimensions : (22, 7)

In [22]:
import sqlite3
import pandas as pd

conn = sqlite3.connect(':memory:')
df.to_sql('avoirs_fmi', conn, index=False, if_exists='replace')

def executer_sql(titre, requete):
    print(f"=== {titre} ===")
    display(pd.read_sql_query(requete, conn))
    print("\n")

# 1. Toutes les observations
executer_sql("1. Toutes les observations", "SELECT * FROM avoirs_fmi;")

# 2. Choix de colonnes + calcul : part du montant tiré dans le montant accordé
executer_sql("2. Part du montant tiré dans le montant accordé", """
SELECT annee_accord, programme, montant_accorde, montant_tire,
       ROUND(montant_tire * 100.0 / montant_accorde, 1) AS part_tire_pct
FROM avoirs_fmi
WHERE montant_accorde > 0;
""")

# 3. LIMIT : les 3 accords les plus récents
executer_sql("3. Les 3 accords les plus récents", """
SELECT annee_accord, programme, montant_accorde FROM avoirs_fmi
ORDER BY annee_accord DESC
LIMIT 3;
""")

# 4. ORDER BY : classement selon le montant accordé
executer_sql("4. Tri selon le montant accordé (décroissant)", """
SELECT annee_accord, programme, montant_accorde
FROM avoirs_fmi
ORDER BY montant_accorde DESC;
""")

# 5. WHERE : accords où le montant accordé est inférieur à 100 millions (100 000 milliers)
executer_sql("5. Accords de moins de 100 millions de DTS", """
SELECT annee_accord, programme, montant_accorde FROM avoirs_fmi
WHERE montant_accorde < 100000
ORDER BY annee_accord;
""")

# 6. COUNT : nombre d'accords dépassant 1 milliard (1 000 000 milliers)
executer_sql("6. Nombre d'accords > 1 milliard de DTS", """
SELECT COUNT(*) AS nb_accords FROM avoirs_fmi
WHERE montant_accorde > 1000000;
""")

# 7. AVG : moyenne des montants accordés depuis 2010
executer_sql("7. Moyenne des montants accordés depuis 2010", """
SELECT ROUND(AVG(montant_accorde)) AS moyenne_accorde
FROM avoirs_fmi
WHERE annee_accord >= 2010;
""")

# 8. MIN / MAX des montants accordés
executer_sql("8. Minimum et maximum des montants accordés", """
SELECT MIN(montant_accorde) AS min_accorde, MAX(montant_accorde) AS max_accorde
FROM avoirs_fmi;
""")

# 9. GROUP BY : moyenne du montant accordé par programme
executer_sql("9. Moyenne du montant accordé par programme", """
SELECT programme,
       COUNT(*) AS nb_accords,
       ROUND(AVG(montant_accorde)) AS moyenne_accordee
FROM avoirs_fmi
GROUP BY programme
ORDER BY moyenne_accordee DESC;
""")

# 10. HAVING : programmes ayant eu au moins un accord individuel supérieur à 1 milliard
executer_sql("10. Programmes avec un accord max ayant dépassé 1 milliard de DTS", """
SELECT programme,
       MAX(montant_accorde) AS max_accorde
FROM avoirs_fmi
GROUP BY programme
HAVING MAX(montant_accorde) > 1000000
ORDER BY max_accorde DESC;
""")

# 11. AND / OR
executer_sql("11. AND : depuis 2010 et montant accordé inférieur à 2.5 milliards", """
SELECT annee_accord, programme, montant_accorde FROM avoirs_fmi
WHERE annee_accord >= 2010 AND montant_accorde < 2500000
ORDER BY annee_accord;
""")

executer_sql("11. OR : montant accordé > 2 milliards OU montant restant > 500 millions", """
SELECT annee_accord, programme, montant_accorde, montant_restant FROM avoirs_fmi
WHERE montant_accorde > 2000000 OR montant_restant > 500000
ORDER BY annee_accord;
""")

# 12. BETWEEN et IN
executer_sql("12. BETWEEN : période d'accord 2015-2019", """
SELECT annee_accord, programme, montant_accorde FROM avoirs_fmi
WHERE annee_accord BETWEEN 2015 AND 2019
ORDER BY annee_accord;
""")

executer_sql("12. IN : années choisies", """
SELECT annee_accord, programme, montant_accorde FROM avoirs_fmi
WHERE annee_accord IN (1990, 2012, 2018, 2023)
ORDER BY annee_accord;
""")

# 13. RANK : classement des accords selon le montant accordé
executer_sql("13. Classement des 8 plus gros accords accordés", """
SELECT annee_accord, programme, montant_accorde,
       RANK() OVER (ORDER BY montant_accorde DESC) AS rang
FROM avoirs_fmi
ORDER BY rang
LIMIT 8;
""")

# 14. Sous-requête : accords sous la moyenne globale
executer_sql("14. Accords dont le montant est sous la moyenne globale", """
SELECT annee_accord, programme, montant_accorde
FROM avoirs_fmi
WHERE montant_accorde < (SELECT AVG(montant_accorde) FROM avoirs_fmi)
ORDER BY annee_accord DESC;
""")

# 15. Synthèse : tendance de l'évolution du montant accordé d'un accord au suivant
executer_sql("15. Synthèse : variation du montant par rapport à l'accord précédent", """
SELECT annee_accord, programme, montant_accorde, variation,
  CASE WHEN variation IS NULL THEN 'Premier accord'
       WHEN variation > 0 THEN 'En hausse'
       WHEN variation < 0 THEN 'En baisse'
       ELSE 'Identique' END AS tendance
FROM (
    SELECT annee_accord, programme, montant_accorde,
           montant_accorde - LAG(montant_accorde) OVER (ORDER BY annee_accord) AS variation
    FROM avoirs_fmi
)
ORDER BY annee_accord DESC;
""")

=== 1. Toutes les observations ===

,programme,date_accord,date_expiration,montant_accorde,montant_tire,montant_restant,annee_accord
0,Resilience and Sustainability Facility,2023-09-28 00:00:00,"Apr 02, 2025",1000000,562500,562500,2023
1,Flexible Credit Line,2023-04-03 00:00:00,"Apr 02, 2025",3726200,0,0,2023
2,Precautionary and Liquidity Line,2018-12-17 00:00:00,"Apr 07, 2020",2150800,2150800,537700,2018
3,Precautionary and Liquidity Line,2016-07-22 00:00:00,"Jul 21, 2018",2504000,0,0,2016
4,Precautionary and Liquidity Line,2014-07-28 00:00:00,"Jul 21, 2016",3235100,0,0,2014
5,Precautionary and Liquidity Line,2012-08-03 00:00:00,"Jul 27, 2014",4117400,0,0,2012
6,Standby Arrangement,1992-01-31 00:00:00,"Mar 31, 1993",91980,18396,0,1992
7,Standby Arrangement,1990-07-20 00:00:00,"Mar 31, 1991",100000,48000,0,1990
8,Standby Arrangement,1988-08-30 00:00:00,"Dec 31, 1989",210000,210000,0,1988
9,Standby Arrangement,1986-12-16 00:00:00,"Apr 30, 1988",230000,230000,0,1986
10,Standby Arrangement,1985-09-12 00:00:00,"Dec 15, 1986",200000,10000,0,1985
11,Standby Arrangement,1983-09-16 00:00:00,"Mar 15, 1985",300000,300000,0,1983
12,Standby Arrangement,1982-04-26 00:00:00,"Apr 25, 1983",281250,281250,0,1982
13,Extended Fund Facility,1981-03-09 00:00:00,"Apr 25, 1982",817050,136500,0,1981
14,Extended Fund Facility,1980-10-08 00:00:00,"Mar 08, 1981",810000,147000,0,1980
15,Standby Arrangement,1971-03-18 00:00:00,"Mar 17, 1972",30000,8250,0,1971
16,Standby Arrangement,1969-12-15 00:00:00,"Dec 14, 1970",25000,10000,0,1969
17,Standby Arrangement,1968-10-27 00:00:00,"Oct 26, 1969",27000,10000,0,1968
18,Standby Arrangement,1967-10-27 00:00:00,"Oct 26, 1968",50000,50000,0,1967
19,Standby Arrangement,1966-09-23 00:00:00,"Sep 22, 1967",50000,0,0,1966
20,Standby Arrangement,1965-09-23 00:00:00,"Sep 22, 1966",45000,0,0,1965
21,Standby Arrangement,1959-11-15 00:00:00,"Nov 14, 1960",25000,0,0,1959

=== 2. Part du montant tiré dans le montant accordé ===

,annee_accord,programme,montant_accorde,montant_tire,part_tire_pct
0,2023,Resilience and Sustainability Facility,1000000,562500,56.3
1,2023,Flexible Credit Line,3726200,0,0.0
2,2018,Precautionary and Liquidity Line,2150800,2150800,100.0
3,2016,Precautionary and Liquidity Line,2504000,0,0.0
4,2014,Precautionary and Liquidity Line,3235100,0,0.0
5,2012,Precautionary and Liquidity Line,4117400,0,0.0
6,1992,Standby Arrangement,91980,18396,20.0
7,1990,Standby Arrangement,100000,48000,48.0
8,1988,Standby Arrangement,210000,210000,100.0
9,1986,Standby Arrangement,230000,230000,100.0
10,1985,Standby Arrangement,200000,10000,5.0
11,1983,Standby Arrangement,300000,300000,100.0
12,1982,Standby Arrangement,281250,281250,100.0
13,1981,Extended Fund Facility,817050,136500,16.7
14,1980,Extended Fund Facility,810000,147000,18.1
15,1971,Standby Arrangement,30000,8250,27.5
16,1969,Standby Arrangement,25000,10000,40.0
17,1968,Standby Arrangement,27000,10000,37.0
18,1967,Standby Arrangement,50000,50000,100.0
19,1966,Standby Arrangement,50000,0,0.0
20,1965,Standby Arrangement,45000,0,0.0
21,1959,Standby Arrangement,25000,0,0.0

=== 3. Les 3 accords les plus récents ===

   annee_accord                               programme  montant_accorde
0          2023  Resilience and Sustainability Facility          1000000
1          2023                    Flexible Credit Line          3726200
2          2018        Precautionary and Liquidity Line          2150800

=== 4. Tri selon le montant accordé (décroissant) ===

    annee_accord                               programme  montant_accorde
0           2012        Precautionary and Liquidity Line          4117400
1           2023                    Flexible Credit Line          3726200
2           2014        Precautionary and Liquidity Line          3235100
3           2016        Precautionary and Liquidity Line          2504000
4           2018        Precautionary and Liquidity Line          2150800
5           2023  Resilience and Sustainability Facility          1000000
6           1981                  Extended Fund Facility           817050
7           1980                  Extended Fund Facility           810000
8           1983                     Standby Arrangement           300000
9           1982                     Standby Arrangement           281250
10          1986                     Standby Arrangement           230000
11          1988                     Standby Arrangement           210000
12          1985                     Standby Arrangement           200000
13          1990                     Standby Arrangement           100000
14          1992                     Standby Arrangement            91980
15          1967                     Standby Arrangement            50000
16          1966                     Standby Arrangement            50000
17          1965                     Standby Arrangement            45000
18          1971                     Standby Arrangement            30000
19          1968                     Standby Arrangement            27000
20          1969                     Standby Arrangement            25000
21          1959                     Standby Arrangement            25000

=== 5. Accords de moins de 100 millions de DTS ===

   annee_accord            programme  montant_accorde
0          1959  Standby Arrangement            25000
1          1965  Standby Arrangement            45000
2          1966  Standby Arrangement            50000
3          1967  Standby Arrangement            50000
4          1968  Standby Arrangement            27000
5          1969  Standby Arrangement            25000
6          1971  Standby Arrangement            30000
7          1992  Standby Arrangement            91980

=== 6. Nombre d'accords > 1 milliard de DTS ===

   nb_accords
0           5

=== 7. Moyenne des montants accordés depuis 2010 ===

   moyenne_accorde
0        2788917.0

=== 8. Minimum et maximum des montants accordés ===

   min_accorde  max_accorde
0        25000      4117400

=== 9. Moyenne du montant accordé par programme ===

                                programme  nb_accords  moyenne_accordee
0                    Flexible Credit Line           1         3726200.0
1        Precautionary and Liquidity Line           4         3001825.0
2  Resilience and Sustainability Facility           1         1000000.0
3                  Extended Fund Facility           2          813525.0
4                     Standby Arrangement          14          118945.0

=== 10. Programmes avec un accord max ayant dépassé 1 milliard de DTS ===

                          programme  max_accorde
0  Precautionary and Liquidity Line      4117400
1              Flexible Credit Line      3726200

=== 11. AND : depuis 2010 et montant accordé inférieur à 2.5 milliards ===

   annee_accord                               programme  montant_accorde
0          2018        Precautionary and Liquidity Line          2150800
1          2023  Resilience and Sustainability Facility          1000000

=== 11. OR : montant accordé > 2 milliards OU montant restant > 500 millions ===

,annee_accord,programme,montant_accorde,montant_restant
0,2012,Precautionary and Liquidity Line,4117400,0
1,2014,Precautionary and Liquidity Line,3235100,0
2,2016,Precautionary and Liquidity Line,2504000,0
3,2018,Precautionary and Liquidity Line,2150800,537700
4,2023,Resilience and Sustainability Facility,1000000,562500
5,2023,Flexible Credit Line,3726200,0

=== 12. BETWEEN : période d'accord 2015-2019 ===

   annee_accord                         programme  montant_accorde
0          2016  Precautionary and Liquidity Line          2504000
1          2018  Precautionary and Liquidity Line          2150800

=== 12. IN : années choisies ===

   annee_accord                               programme  montant_accorde
0          1990                     Standby Arrangement           100000
1          2012        Precautionary and Liquidity Line          4117400
2          2018        Precautionary and Liquidity Line          2150800
3          2023  Resilience and Sustainability Facility          1000000
4          2023                    Flexible Credit Line          3726200

=== 13. Classement des 8 plus gros accords accordés ===

   annee_accord                               programme  montant_accorde  rang
0          2012        Precautionary and Liquidity Line          4117400     1
1          2023                    Flexible Credit Line          3726200     2
2          2014        Precautionary and Liquidity Line          3235100     3
3          2016        Precautionary and Liquidity Line          2504000     4
4          2018        Precautionary and Liquidity Line          2150800     5
5          2023  Resilience and Sustainability Facility          1000000     6
6          1981                  Extended Fund Facility           817050     7
7          1980                  Extended Fund Facility           810000     8

=== 14. Accords dont le montant est sous la moyenne globale ===

    annee_accord               programme  montant_accorde
0           1992     Standby Arrangement            91980
1           1990     Standby Arrangement           100000
2           1988     Standby Arrangement           210000
3           1986     Standby Arrangement           230000
4           1985     Standby Arrangement           200000
5           1983     Standby Arrangement           300000
6           1982     Standby Arrangement           281250
7           1981  Extended Fund Facility           817050
8           1980  Extended Fund Facility           810000
9           1971     Standby Arrangement            30000
10          1969     Standby Arrangement            25000
11          1968     Standby Arrangement            27000
12          1967     Standby Arrangement            50000
13          1966     Standby Arrangement            50000
14          1965     Standby Arrangement            45000
15          1959     Standby Arrangement            25000

=== 15. Synthèse : variation du montant par rapport à l'accord précédent ===

,annee_accord,programme,montant_accorde,variation,tendance
0,2023,Resilience and Sustainability Facility,1000000,-1150800.0,En baisse
1,2023,Flexible Credit Line,3726200,2726200.0,En hausse
2,2018,Precautionary and Liquidity Line,2150800,-353200.0,En baisse
3,2016,Precautionary and Liquidity Line,2504000,-731100.0,En baisse
4,2014,Precautionary and Liquidity Line,3235100,-882300.0,En baisse
5,2012,Precautionary and Liquidity Line,4117400,4025420.0,En hausse
6,1992,Standby Arrangement,91980,-8020.0,En baisse
7,1990,Standby Arrangement,100000,-110000.0,En baisse
8,1988,Standby Arrangement,210000,-20000.0,En baisse
9,1986,Standby Arrangement,230000,30000.0,En hausse
10,1985,Standby Arrangement,200000,-100000.0,En baisse
11,1983,Standby Arrangement,300000,18750.0,En hausse
12,1982,Standby Arrangement,281250,-535800.0,En baisse
13,1981,Extended Fund Facility,817050,7050.0,En hausse
14,1980,Extended Fund Facility,810000,780000.0,En hausse
15,1971,Standby Arrangement,30000,5000.0,En hausse
16,1969,Standby Arrangement,25000,-2000.0,En baisse
17,1968,Standby Arrangement,27000,-23000.0,En baisse
18,1967,Standby Arrangement,50000,0.0,Identique
19,1966,Standby Arrangement,50000,5000.0,En hausse
20,1965,Standby Arrangement,45000,20000.0,En hausse
21,1959,Standby Arrangement,25000,NaN,Premier accord